name: CI

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 0 * * 6'

jobs:
  test:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.2', '7.3', '7.4']

    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        uses: php-actions/composer@v5
        with:
          php_version: ${{ matrix.php-versions }}

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v2
        with:
          version: 8.0.0
          php_version: ${{ matrix.php-versions }}
          configuration: phpunit.xml
          bootstrap: vendor/autoload.php
